apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: calc-app 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: calc-app
    spec:
      containers:
      - name: calc-app
        image: docker.io/sjostric/calc-app:1.0.0-SNAPSHOT
        ports:
        - containerPort: 8080 
